blank_issues_enabled: false
contact_links:
  - name: SparkFun - Technical Assistance webpage
    url: https://www.sparkfun.com/technical_assistance
    about: Technical assistance resources
  - name: SparkFun Forum
    url: https://forum.sparkfun.com/
    about: Forum for SparkFun products