name: Hardware Issue
description: Report any problems with the hardware design or operation
title: "[HW]: "
labels: ["Status: Issue Reported", "hardware"]
body:
  - type: markdown
    attributes:
      value: dfgdfg