name: Issue - Hookup Guide 📝 ✍
description: Report any problems related to the documentation
title: "Docs Error: "
labels: ["Status: Issue Reported", "documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure an issue is being reported; this is not an appropriate channel for questions or assistance on a product. Good examples of issues that should be submitted here are broken links, typos, or outdated information.

        Before reporting a new issue, please search the [list of existing documentation issues](https://github.com/sparkfun/git-test/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation+) to avoid creating duplicates. Otherwise, if you spotted an unlisted error in our documentation, please continue filling out this form: 
        - Provide a concise title summarizing the problem (eg. **Typo in Hardware Overview section*- or **Misspelled worlds as wosrld**)
        - Screenshots are extremely helpful and it is easy to [attach files](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) into GitHub issues:
          | Drag and Drop | Select to Attach |
          | :-----------: | :--------------: |
          | <img alt="Attachments animated GIF" title="Click to enlarge" src="https://docs.github.com/assets/cb-726253/images/help/pull_requests/dragging_images.gif" width="350"> | <img alt="Select attachments from computer" title="Click to enlarge" src="https://docs.github.com/assets/cb-42604/mw-1000/images/help/pull_requests/select-bar.webp" width="350"> |
  - type: dropdown
    id: issue_type
    attributes:
      label: Problem
      description: What type of problem have you found?
      options:
        - Typo - Spelling or Grammatical
        - Broken Hyperlink
        - Incorrect Information
        - Politically Incorrect
        - Other
    validations:
      required: true
  - type: input
    id: error
    attributes:
      label: Error
      description: State the exact problem
      placeholder: eg. Broken hyperlink (example.com) to Arduino library in Example 1
    validations:
      required: false
  - type: textarea
    id: location
    attributes:
      label: Location
      description: What is the location of the issue?
      placeholder: |
        Add a screenshot (see instructions above) or link the line in markdown file
        - Make sure the relative location can be determined from the screenshot
        - The link should have this format: <repo url>/docs/<directory>/<file name>.md?plain=1#L<line number>
    validations:
      required: false
  - type: textarea
    id: correction
    attributes:
      label: Suggested Correction
      description: How could this problem be corrected?
      placeholder: |
        For any politically incorrect statements, we apologize for our ignorance of the issue 😔😞😨😱. Sometimes these can be tricky for the uninitiated 🤔, so please provide us with a suggestion to improve our wording. Thanks!

        Feel free to skip this section, if the correction is obvious from the information above (eg. Title states: "Misspelled worlds as wosrld")
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Please include any documents and other information that you'd like to add
      placeholder: |
        For any politically incorrect statements, please provide us with some information or articles. We'd be happy to spread awareness to our colleagues, here at SparkFun 📨

        When referencing information from a datasheet:
        - Specify, link, or attach the datasheet.
        - Provide the section that the information is in (eg. section 5.1.2)
        - For longer sections quote the information exactly or provide a screenshot
    validations:
      required: false
  - type: checkboxes
    id: confirmation
    attributes:
      label: I have checked existing issues, online documentation, and the troubleshooting guide
      description: You agree to check all the resources above before opening a new issue.
      options:
        - label: No, I am not posting a question for technical assistance.
          required: true
        - label: Yes, I have confirmed this is not a duplicate issue.
          required: true