name: Hardware Functionality âš ï¸ â›” ðŸ™… ðŸš« ðŸ¤· ðŸš§ ðŸ¤–ðŸ’¥, ðŸ¤–ðŸª›, ðŸ¤–ðŸ› ï¸
description: Report any problems with an expected hardware behavior
title: "Operation: "
labels: ["Status: Issue Reported", "hardware", "operation"]
body:
  - type: markdown
    attributes:
      value: |
        > Provide a concise title summarizing the problem (eg. **Power LED on with switch in the off position** or **Charge circuit not working charging**)
  - type: checkboxes
    id: new_issue
    attributes:
      label: This is a new issue
      # description: All the boxes must be checked to proceed
      options:
        - label: I am not posting a question or looking for [technical assistance](https://www.sparkfun.com/technical_assistance).
          required: true
        - label: I have confirmed this is not a duplicate [issue](https://github.com/sparkfun/git-test/issues?q=is%3Aissue+label%3Ahardware+).
          required: true
  - type: markdown
    attributes:
      value: |
        > Please make sure an issue is being reported; this is not an appropriate channel for questions or assistance on a product.
        > - Good examples of issues that should be submitted here are broken links, typos, or outdated information.
        > - If you are looking for technical assistance, please head over to our [technical assistance page](https://www.sparkfun.com/technical_assistance).
        > - If you need to report a defect in our product for a replacement, please check out our [return policy](https://www.sparkfun.com/returns) and fill out the form, if you qualify for a return.
        > 
        > Before reporting a new issue, please search the [list of hardware issues](https://github.com/sparkfun/git-test/issues?q=is%3Aissue+label%3Ahardware+) to avoid creating duplicates. Otherwise, if you spotted an unlisted error in our documentation, please continue filling out this form.
  - type: checkboxes
    id: basic_troubleshooting
    attributes:
      label: I have tried some basic troubleshooting
      # description: All the boxes must be checked to proceed
      options:
        - label: I have tested my board with a basic example from the [hookup guide]().
          required: false
        - label: I already checked the [troubleshooting guide](https://learn.sparkfun.com/tutorials/sparkfun-troubleshooting-tips) for potential issues.
          required: false
  - type: markdown
    attributes:
      value: |
        > For most issues, we will ask that a minimal level of testing and troubleshooting with the board be attempted.
        > - Performing a basic test using a hardware setup with a software example that is known to work will help to establish a baseline (if your board is working or not).
        > - Good examples of issues that should be troubleshot:
        >    - 
        >    - 
        >    - 
        >    - 
        >
        > If you have omitted one/both of these steps, please provide us with a valid explanation at the end of this form. Otherwise, our initial response will be a request to perform these steps.
        >
        > Please add your notes for any additional troubleshooting and/or testing at the end of this form.
  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What type of problem have you found?
      options:
        - Board Feature
        - Example Setup
        - Other
    validations:
      required: true
  - type: input
    id: statement
    attributes:
      label: Problem Statement
      description: State the exact problem
      placeholder: eg. **Bad current leak through <net name> in low power mode** or ****
    validations:
      required: true
  - type: textarea
    id: testing
    attributes:
      label: How did you determine this issue
      description: How do we duplicate this issue?
      placeholder: |
        Add a picture or screenshot (see instructions below)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > ***How to attach an image:***
        > Screenshots are extremely helpful and it is easy to [attach files](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) into GitHub issues:
        > | Drag and Drop | Select to Attach |
        > | :-----------: | :--------------: |
        > | <img alt="Attachments animated GIF" title="Click to enlarge" src="https://docs.github.com/assets/cb-726253/images/help/pull_requests/dragging_images.gif" width="350"> | <img alt="Select attachments from computer" title="Click to enlarge" src="https://docs.github.com/assets/cb-42604/mw-1000/images/help/pull_requests/select-bar.webp" width="350"> |
  - type: input
    id: board
    attributes:
      label: Dev. Board
      description: On which Board does this issue occur?
      placeholder: eg. ESP32 Dev Module, ESP32-S2, LilyGo TTGO LoRa32...
    validations:
      required: true
  - type: textarea
    id: dev_board
    attributes:
      label: Device Description
      description: What development board or other hardware is the chip attached to?
      placeholder: ex. DevKitC, a plain module on a breadboard, etc. If your hardware is custom or unusual, please attach a photo.
    validations:
       required: true
  - type: textarea
    id: other-hw
    attributes:
      label: Hardware Configuration
      description: Describe your hardware setup
      placeholder: ex. GPIO 18 & 19 are connected to I2C devices (w/ picture(s) of the setup attached).
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: On what OS does this issue occur?
      placeholder: ex. macOS 12.1, Windows 11...
    validations:
      required: true
  - type: input
    id: ide
    attributes:
      label: IDE Name
      description: What IDE are you using?
      placeholder: eg. Arduino IDE, PlatformIO, Sloeber...
    validations:
      required: true
  - type: input
    id: library
    attributes:
      label: Library/Package
      description: Which library (or package) and version are you using?
      placeholder: eg. `[SparkFun BMA400 Arduino Library - v1.0.0](https://github.com/sparkfun/SparkFun_BMA400_Arduino_Library/releases/tag/v1.0.0)`
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your problem here and the expected behavior
      placeholder: ex. Can't connect/weird behavior/wrong function/missing parameter...
    validations:
      required: true
  - type: textarea
    id: sketch
    attributes:
      label: Sketch
      description: Please provide a full minimal sketch/code which can be run to reproduce your issue
      placeholder: ex. The related part of the code to replicate the issue
      render: cpp
    validations:
      required: true
  - type: textarea
    id: debug
    attributes:
      label: Debug Message
      description: Please provide a debug message or error message. If you have a Guru Meditation Error or Backtrace, please decode it with [ExceptionDecoder](https://github.com/me-no-dev/EspExceptionDecoder)
      placeholder: Enable Core debug level - Debug on the tools menu of Arduino IDE, then put the serial output here.
      render: plain
    validations:
      required: true      
  - type: textarea
    id: other-remarks
    attributes:
      label: Other Steps to Reproduce 
      description: Is there any other information you can think of which will help us reproduce this problem? Any additional info can be added as well.
      placeholder: ex. I also tried it on another OS, HW...it works correctly on that setup.
  - type: checkboxes
    id: confirmation
    attributes:
      label: I have checked existing issues, online documentation, and the troubleshooting guide
      description: You agree to check all the resources above before opening a new issue.
      options:
      - label: No, I am not posting a question for technical assistance.
        required: true
      - label: Yes, I confirm I have checked the existing issues.
        required: true
      - label: Yes, I confirm I have checked the online documentation.
        required: true
      - label: Yes, I confirm I have checked the troubleshooting guide.
        required: true