name: Hookup Guide Issue
description: Report any problem related to the documentation
labels: ["Status: Issue Reported", "documentation"]
body:
  - type: markdown
    attributes:
      value: |
        * Before reporting a documentation issue, *please check and search the [list of existing documentation issues](https://github.com/sparkfun/git-test/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation+)*.
        * Provide a concise title (eg. **Typo in Hawdrware Overview section**)
        * Screenshots are extremely helpful and easy to copy/paste into GitHub.
          ![Example of pasting in a screenshot]()
        * If you reference information from a datasheet, please specify or link the datasheet and provide the section that the information is in (eg. the protocol manual, section 5.1.2).
  - type: dropdown
    id: issue_type
    attributes:
      label: Problem
      description: What type of problem have you found?
      options:
        - Typo - Spelling or Grammatical
        - Broken Hyperlink
        - Incorrect Information
        - Other
    validations:
      required: true
  - type: input
    id: error
    attributes:
      label: Error
      description: What is the exact problem?
      placeholder: eg. broken hyperlink (example.com)
    validations:
      required: false
  - type: input
    id: location
    attributes:
      label: Location
      description: What is the location of the issue?
      placeholder: eg. line in markdown file (<repo url>/docs/<file name>.md?plain=1#L<line number>)
    validations:
      required: false
  - type: textarea
    id: correction
    attributes:
      label: Suggested Correction
      description: How could this problem be corrected?
    validations:
      required: true
  - type: checkboxes
    id: confirmation
    attributes:
      label: I have checked existing issues, online documentation, and the troubleshooting guide
      description: You agree to check all the resources above before opening a new issue.
      options:
        - label: I confirm I have checked existing issues, online documentation, and the troubleshooting guide.
          required: true
